export interface Student {
    student_id: Buffer;
    user_id: number;
    first_name: string;
    middle_name?: string;
    last_name: string;
    extension_name?: string;
    sex: string;
    place_of_birth: string;
    birthdate: Date;
    height?: number;
    weight?: number;
    permanent_address: string;
    current_address: string;
    email: string;
    mobile_number: string;
    is_solo_parent: boolean;
    is_child_of_solo_parent: boolean;
    is_indigenous_people: boolean;
    indigenous_group?: string;
    is_sped: boolean;
    is_pwd: boolean;
    emergency_contact_name: string;
    emergency_contact_number: string;
    academic_strand: string;
    program_name: string;
    award_honor?: string;
    organization?: string;
    school_name: string;
    school_address: string;
    school_type: "Private" | "Public";
    year_of_graduation: number;
    current_program_name: string;
    current_year_level: number;
    current_award_honor?: string;
    current_organization?: string;
    current_school_name: string;
    current_school_address: string;
    current_school_type: "Private" | "Public";
    father_last_name: string;
    father_first_name: string;
    father_middle_name?: string;
    father_extension?: string;
    father_occupation: string;
    father_income?: number;
    father_mobile_number: string;
    mother_maiden_last_name: string;
    mother_maiden_first_name: string;
    mother_maiden_middle_name?: string;
    mother_maiden_extension?: string;
    mother_occupation: string;
    mother_income?: number;
    mother_mobile_number: string;
    guardian_last_name: string;
    guardian_first_name: string;
    guardian_middle_name?: string;
    guardian_extension?: string;
    guardian_occupation: string;
    guardian_income?: number;
    guardian_mobile_number: string;
    number_of_siblings: number;
    emergency_contact_name2: string;
    emergency_contact_number2: string;
    applicationForm: string;
    created_at?: string;
    updated_at?: string;
    created_by?: Buffer;
    updated_by?: Buffer;
    recordStatus?: boolean;
}

export type Sibling = {
    student_id: number;
    sibling_name: string;
    sibling_bdate: Date;
    sibling_age: number;
    sibling_status: "Single" | "Married" | "Divorced" | "Widowed";
    living_with_parents: boolean;
    own_house: boolean;
    created_at?: Date;
    updated_at?: Date;
    created_by?: Buffer;
    updated_by?: Buffer;
    recordStatus?: boolean;
};